# Generated by Django 2.0.3 on 2018-08-24 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('matricula', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prancheta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome_do_municipio', models.TextField()),
                ('UF', models.TextField()),
                ('nome_agente', models.TextField()),
                ('numero_folha', models.PositiveIntegerField()),
                ('endereco', models.TextField()),
                ('tipo_imovel', models.CharField(choices=[('1-Residência', 'residência'), ('2-Comercio', 'comercio'), ('3-Terreno', 'terreno'), ('4-Ponto estrategico', 'ponto estrategico'), ('5-Outros(Hospitais,Escolas, Órgãos publicos)', 'Outros')], max_length=20)),
                ('Imoveis_trabalhados', models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=3)),
                ('Imoveis_fechados', models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=3)),
                ('Imoveis_recusados', models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=3)),
                ('Imoveis_recuperados', models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=3)),
                ('Focos', models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=3)),
                ('Tratamento_larvicida', models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.TextField()),
                ('rua', models.TextField()),
                ('barrio', models.TextField()),
                ('cidade', models.TextField()),
                ('numero_casa', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome_agente_visita', models.TextField()),
                ('codigo_visita', models.PositiveIntegerField()),
            ],
        ),
    ]
