# Generated by Django 2.0.4 on 2018-10-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prancheta',
            old_name='Focos',
            new_name='focos',
        ),
        migrations.RenameField(
            model_name='prancheta',
            old_name='Imoveis_fechados',
            new_name='imoveis_fechados',
        ),
        migrations.RenameField(
            model_name='prancheta',
            old_name='Imoveis_recuperados',
            new_name='imoveis_recuperados',
        ),
        migrations.RenameField(
            model_name='prancheta',
            old_name='Imoveis_recusados',
            new_name='imoveis_recusados',
        ),
        migrations.RenameField(
            model_name='prancheta',
            old_name='Imoveis_trabalhados',
            new_name='imoveis_trabalhados',
        ),
        migrations.RenameField(
            model_name='prancheta',
            old_name='Tratamento_larvicida',
            new_name='tratamento_larvicida',
        ),
        migrations.RemoveField(
            model_name='prancheta',
            name='data',
        ),
        migrations.RemoveField(
            model_name='prancheta',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='prancheta',
            name='nome_agente',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='nome_agente_visita',
        ),
        migrations.AddField(
            model_name='prancheta',
            name='dados_da_visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salus.Visita'),
        ),
        migrations.AddField(
            model_name='visita',
            name='agente_da_visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salus.Extra'),
        ),
        migrations.AddField(
            model_name='visita',
            name='residencia_visitada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salus.Residencia'),
        ),
    ]
