# Generated by Django 2.0 on 2018-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0003_residencia_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='bairro',
            field=models.TextField(default=''),
        ),
    ]
