# Generated by Django 2.0 on 2018-10-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0004_auto_20181026_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prancheta',
            name='imoveis_fechados',
        ),
        migrations.RemoveField(
            model_name='prancheta',
            name='imoveis_recuperados',
        ),
        migrations.RemoveField(
            model_name='prancheta',
            name='imoveis_recusados',
        ),
        migrations.RemoveField(
            model_name='prancheta',
            name='numero_folha',
        ),
        migrations.AlterField(
            model_name='prancheta',
            name='tipo_imovel',
            field=models.CharField(choices=[('1-Residência', 'residência'), ('2-Comercio', 'comercio'), ('3-Terreno', 'terreno'), ('4-Outros(Hospitais,Escolas, Órgãos publicos)', 'Outros')], max_length=20),
        ),
    ]
