# Generated by Django 2.0 on 2018-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0005_auto_20181026_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prancheta',
            name='UF',
            field=models.CharField(choices=[('Alagoas', 'Alagoas'), ('Bahia', 'Bahia'), ('Ceará', 'Ceará'), ('Maranhão', 'Maranhão'), ('Paraíba', 'Paraíba'), ('Pernambuco', 'Pernambuco'), ('Piauí', 'Piauí'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Sergipe', 'Sergipe')], max_length=50),
        ),
    ]
