# Generated by Django 2.0 on 2018-10-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0006_auto_20181026_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificar_visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('imoveis_fechados', models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=3)),
                ('imoveis_recusados', models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=3)),
            ],
        ),
    ]
