# Generated by Django 2.0 on 2018-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0011_auto_20181027_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='bairro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
    ]
