# Generated by Django 2.0 on 2018-10-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0013_auto_20181027_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='Cidade',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
