# Generated by Django 2.0 on 2018-10-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0014_bairro_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='Cidade',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
