# Generated by Django 2.0 on 2018-10-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0015_auto_20181027_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='cidade',
        ),
        migrations.AlterField(
            model_name='bairro',
            name='Cidade',
            field=models.CharField(default='', max_length=200),
        ),
    ]
