# Generated by Django 2.0 on 2018-10-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0016_auto_20181027_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='bairro',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='bairro',
            name='Cidade',
        ),
        migrations.AlterField(
            model_name='residencia',
            name='bairro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Bairro'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='rua',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Rua'),
        ),
        migrations.AddField(
            model_name='rua',
            name='bairro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Bairro'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Estado'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Cidade'),
        ),
        migrations.AddField(
            model_name='residencia',
            name='cidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Cidade'),
        ),
        migrations.AddField(
            model_name='residencia',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Estado'),
        ),
    ]
