# Generated by Django 2.0 on 2018-11-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0022_cidade_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
