# Generated by Django 2.0 on 2018-11-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0022_cidade_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='trajeto',
            field=models.ManyToManyField(to='salus.Rua'),
        ),
    ]
