# Generated by Django 2.0 on 2018-11-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0025_auto_20181106_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='trajeto',
        ),
        migrations.AddField(
            model_name='rota',
            name='trajeto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Bairro'),
        ),
    ]
