# Generated by Django 2.0 on 2018-11-06 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0028_auto_20181106_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rota',
            old_name='trajeto',
            new_name='bairro',
        ),
        migrations.AddField(
            model_name='rota',
            name='ruas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Rua'),
        ),
    ]
