# Generated by Django 2.0 on 2018-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0029_auto_20181106_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='ruas',
        ),
        migrations.AddField(
            model_name='rota',
            name='ruas',
            field=models.ManyToManyField(to='salus.Rua'),
        ),
    ]
