# Generated by Django 2.0 on 2018-11-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0030_auto_20181106_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='nome',
        ),
    ]
