# Generated by Django 2.0 on 2018-11-07 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0031_remove_rota_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Área x', max_length=25, unique=True)),
                ('caminho', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Rota')),
            ],
        ),
    ]
