# Generated by Django 2.0 on 2018-11-07 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0032_trajeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajeto',
            name='caminho',
        ),
        migrations.AddField(
            model_name='rota',
            name='nome',
            field=models.CharField(default='Área x', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='trajeto',
            name='nome',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='salus.Rota'),
        ),
    ]
