# Generated by Django 2.0 on 2018-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0034_auto_20181106_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resgistrar_observacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='visita',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
