# Generated by Django 2.0 on 2018-11-07 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salus', '0035_auto_20181107_1303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resgistrar_observacao',
        ),
        migrations.AddField(
            model_name='trajeto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
