# Generated by Django 2.0 on 2018-11-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0036_auto_20181107_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prancheta',
            old_name='nome_do_municipio',
            new_name='observacao',
        ),
        migrations.RemoveField(
            model_name='prancheta',
            name='UF',
        ),
        migrations.AlterField(
            model_name='prancheta',
            name='dados_da_visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salus.Visita'),
        ),
    ]
