# Generated by Django 2.0 on 2018-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0037_auto_20181108_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prancheta',
            name='focos',
            field=models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=5),
        ),
        migrations.AlterField(
            model_name='prancheta',
            name='imoveis_trabalhados',
            field=models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=5),
        ),
        migrations.AlterField(
            model_name='prancheta',
            name='tipo_imovel',
            field=models.CharField(choices=[('1-Residência', 'residência'), ('2-Comercio', 'comercio'), ('3-Terreno', 'terreno'), ('4-Outros(Hospitais,Escolas, Órgãos publicos)', 'Outros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='prancheta',
            name='tratamento_larvicida',
            field=models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=5),
        ),
    ]
