# Generated by Django 2.0 on 2018-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0038_auto_20181108_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prancheta',
            name='dados_da_visita',
        ),
        migrations.AddField(
            model_name='prancheta',
            name='dados_da_visita',
            field=models.ManyToManyField(null=True, to='salus.Residencia'),
        ),
    ]
