# Generated by Django 2.0 on 2018-11-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0039_auto_20181108_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prancheta',
            name='dados_da_visita',
        ),
        migrations.AddField(
            model_name='prancheta',
            name='dados_da_visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salus.Residencia'),
        ),
    ]
