# Generated by Django 2.0 on 2018-11-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0040_auto_20181108_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
