# Generated by Django 2.0.7 on 2018-11-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0023_auto_20181107_0843'),
        ('salus', '0041_auto_20181108_0940'),
    ]

    operations = [
    ]
