# Generated by Django 2.0.7 on 2018-11-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0042_merge_20181117_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificar_visita',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='justificar_visita',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='justificar_visita',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='justificar_visita',
            name='rua',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='justificar_visita',
            name='imoveis_fechados',
            field=models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=10),
        ),
        migrations.AlterField(
            model_name='justificar_visita',
            name='imoveis_recusados',
            field=models.CharField(choices=[('1-Sim', 'sim'), ('2-Não', 'nao')], max_length=10),
        ),
    ]
