# Generated by Django 2.0.7 on 2018-11-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salus', '0043_auto_20181117_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificar_visita',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='justificar_visita',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='justificar_visita',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='justificar_visita',
            name='rua',
            field=models.CharField(default='', max_length=100),
        ),
    ]
